export const statusDict: Record<number, string> = {
    0: 'HEALTHY',
    3: 'ASLEEP',
    4: 'POISON',
    5: 'BURNED',
    6: 'FROZEN',
    7: 'PARALYZED'
};

export const typeDict: Record<number, string> = {
    0: 'NORMAL',
    1: 'FIGHTING',
    2: 'FLYING',
    3: 'POISON',
    4: 'GROUND',
    5: 'ROCK',
    7: 'BUG',
    8: 'GHOST',
    20: 'FIRE',
    21: 'WATER',
    22: 'GRASS',
    23: 'ELECTRIC',
    24: 'PSYCHIC',
    25: 'ICE',
    26: 'DRAGON'
};

export const dexDict: Record<number, { name: string, pokedexNo: string }> = {
    1: { 'name': 'rhydon', 'pokedexNo': '112' },
    2: { 'name': 'kangaskhan', 'pokedexNo': '115' },
    3: { 'name': 'nidoran_m', 'pokedexNo': '032' },
    4: { 'name': 'clefairy', 'pokedexNo': '035' },
    5: { 'name': 'spearow', 'pokedexNo': '021' },
    6: { 'name': 'voltorb', 'pokedexNo': '100' },
    7: { 'name': 'nidoking', 'pokedexNo': '034' },
    8: { 'name': 'slowbro', 'pokedexNo': '080' },
    9: { 'name': 'ivysaur', 'pokedexNo': '002' },
    10: { 'name': 'exeggutor', 'pokedexNo': '103' },
    11: { 'name': 'lickitung', 'pokedexNo': '108' },
    12: { 'name': 'exeggcute', 'pokedexNo': '102' },
    13: { 'name': 'grimer', 'pokedexNo': '088' },
    14: { 'name': 'gengar', 'pokedexNo': '094' },
    15: { 'name': 'nidoran_f', 'pokedexNo': '029' },
    16: { 'name': 'nidoqueen', 'pokedexNo': '031' },
    17: { 'name': 'cubone', 'pokedexNo': '104' },
    18: { 'name': 'rhyhorn', 'pokedexNo': '111' },
    19: { 'name': 'lapras', 'pokedexNo': '131' },
    20: { 'name': 'arcanine', 'pokedexNo': '059' },
    21: { 'name': 'mew', 'pokedexNo': '151' },
    22: { 'name': 'gyarados', 'pokedexNo': '130' },
    23: { 'name': 'shellder', 'pokedexNo': '090' },
    24: { 'name': 'tentacool', 'pokedexNo': '072' },
    25: { 'name': 'gastly', 'pokedexNo': '092' },
    26: { 'name': 'scyther', 'pokedexNo': '123' },
    27: { 'name': 'staryu', 'pokedexNo': '120' },
    28: { 'name': 'blastoise', 'pokedexNo': '009' },
    29: { 'name': 'pinsir', 'pokedexNo': '127' },
    30: { 'name': 'tangela', 'pokedexNo': '114' },
    31: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    32: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    33: { 'name': 'growlithe', 'pokedexNo': '058' },
    34: { 'name': 'onix', 'pokedexNo': '095' },
    35: { 'name': 'fearow', 'pokedexNo': '022' },
    36: { 'name': 'pidgey', 'pokedexNo': '016' },
    37: { 'name': 'slowpoke', 'pokedexNo': '079' },
    38: { 'name': 'kadabra', 'pokedexNo': '064' },
    39: { 'name': 'graveler', 'pokedexNo': '075' },
    40: { 'name': 'chansey', 'pokedexNo': '113' },
    41: { 'name': 'machoke', 'pokedexNo': '067' },
    42: { 'name': 'mr.mime', 'pokedexNo': '122' },
    43: { 'name': 'hitmonlee', 'pokedexNo': '106' },
    44: { 'name': 'hitmonchan', 'pokedexNo': '107' },
    45: { 'name': 'arbok', 'pokedexNo': '024' },
    46: { 'name': 'parasect', 'pokedexNo': '047' },
    47: { 'name': 'psyduck', 'pokedexNo': '054' },
    48: { 'name': 'drowzee', 'pokedexNo': '096' },
    49: { 'name': 'golem', 'pokedexNo': '076' },
    50: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    51: { 'name': 'magmar', 'pokedexNo': '126' },
    52: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    53: { 'name': 'electabuzz', 'pokedexNo': '125' },
    54: { 'name': 'magneton', 'pokedexNo': '082' },
    55: { 'name': 'koffing', 'pokedexNo': '109' },
    56: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    57: { 'name': 'mankey', 'pokedexNo': '056' },
    58: { 'name': 'seel', 'pokedexNo': '086' },
    59: { 'name': 'diglett', 'pokedexNo': '050' },
    60: { 'name': 'tauros', 'pokedexNo': '128' },
    61: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    62: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    63: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    64: { 'name': 'farfetchd', 'pokedexNo': '083' },
    65: { 'name': 'venonat', 'pokedexNo': '048' },
    66: { 'name': 'dragonite', 'pokedexNo': '149' },
    67: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    68: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    69: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    70: { 'name': 'doduo', 'pokedexNo': '084' },
    71: { 'name': 'poliwag', 'pokedexNo': '060' },
    72: { 'name': 'jynx', 'pokedexNo': '124' },
    73: { 'name': 'moltres', 'pokedexNo': '146' },
    74: { 'name': 'articuno', 'pokedexNo': '144' },
    75: { 'name': 'zapdos', 'pokedexNo': '145' },
    76: { 'name': 'ditto', 'pokedexNo': '132' },
    77: { 'name': 'meowth', 'pokedexNo': '052' },
    78: { 'name': 'krabby', 'pokedexNo': '098' },
    79: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    80: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    81: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    82: { 'name': 'vulpix', 'pokedexNo': '037' },
    83: { 'name': 'ninetales', 'pokedexNo': '038' },
    84: { 'name': 'pikachu', 'pokedexNo': '025' },
    85: { 'name': 'raichu', 'pokedexNo': '026' },
    86: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    87: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    88: { 'name': 'dratini', 'pokedexNo': '147' },
    89: { 'name': 'dragonair', 'pokedexNo': '148' },
    90: { 'name': 'kabuto', 'pokedexNo': '140' },
    91: { 'name': 'kabutops', 'pokedexNo': '141' },
    92: { 'name': 'horsea', 'pokedexNo': '116' },
    93: { 'name': 'seadra', 'pokedexNo': '117' },
    94: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    95: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    96: { 'name': 'sandshrew', 'pokedexNo': '027' },
    97: { 'name': 'sandslash', 'pokedexNo': '028' },
    98: { 'name': 'omanyte', 'pokedexNo': '138' },
    99: { 'name': 'omastar', 'pokedexNo': '139' },
    100: { 'name': 'jigglypuff', 'pokedexNo': '039' },
    101: { 'name': 'wigglytuff', 'pokedexNo': '040' },
    102: { 'name': 'eevee', 'pokedexNo': '133' },
    103: { 'name': 'flareon', 'pokedexNo': '136' },
    104: { 'name': 'jolteon', 'pokedexNo': '135' },
    105: { 'name': 'vaporeon', 'pokedexNo': '134' },
    106: { 'name': 'machop', 'pokedexNo': '066' },
    107: { 'name': 'zubat', 'pokedexNo': '041' },
    108: { 'name': 'ekans', 'pokedexNo': '023' },
    109: { 'name': 'paras', 'pokedexNo': '046' },
    110: { 'name': 'poliwhirl', 'pokedexNo': '061' },
    111: { 'name': 'poliwrath', 'pokedexNo': '062' },
    112: { 'name': 'weedle', 'pokedexNo': '013' },
    113: { 'name': 'kakuna', 'pokedexNo': '014' },
    114: { 'name': 'beedrill', 'pokedexNo': '015' },
    115: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    116: { 'name': 'dodrio', 'pokedexNo': '085' },
    117: { 'name': 'primeape', 'pokedexNo': '057' },
    118: { 'name': 'dugtrio', 'pokedexNo': '051' },
    119: { 'name': 'venomoth', 'pokedexNo': '049' },
    120: { 'name': 'dewgong', 'pokedexNo': '087' },
    121: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    122: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    123: { 'name': 'caterpie', 'pokedexNo': '010' },
    124: { 'name': 'metapod', 'pokedexNo': '011' },
    125: { 'name': 'butterfree', 'pokedexNo': '012' },
    126: { 'name': 'machamp', 'pokedexNo': '068' },
    127: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    128: { 'name': 'golduck', 'pokedexNo': '055' },
    129: { 'name': 'hypno', 'pokedexNo': '097' },
    130: { 'name': 'golbat', 'pokedexNo': '042' },
    131: { 'name': 'mewtwo', 'pokedexNo': '150' },
    132: { 'name': 'snorlax', 'pokedexNo': '143' },
    133: { 'name': 'magikarp', 'pokedexNo': '129' },
    134: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    135: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    136: { 'name': 'muk', 'pokedexNo': '089' },
    137: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    138: { 'name': 'kingler', 'pokedexNo': '099' },
    139: { 'name': 'cloyster', 'pokedexNo': '091' },
    140: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    141: { 'name': 'electrode', 'pokedexNo': '101' },
    142: { 'name': 'clefable', 'pokedexNo': '036' },
    143: { 'name': 'weezing', 'pokedexNo': '110' },
    144: { 'name': 'persian', 'pokedexNo': '053' },
    145: { 'name': 'marowak', 'pokedexNo': '105' },
    146: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    147: { 'name': 'haunter', 'pokedexNo': '093' },
    148: { 'name': 'abra', 'pokedexNo': '063' },
    149: { 'name': 'alakazam', 'pokedexNo': '065' },
    150: { 'name': 'pidgeotto', 'pokedexNo': '017' },
    151: { 'name': 'pidgeot', 'pokedexNo': '018' },
    152: { 'name': 'starmie', 'pokedexNo': '121' },
    153: { 'name': 'bulbasaur', 'pokedexNo': '001' },
    154: { 'name': 'venusaur', 'pokedexNo': '003' },
    155: { 'name': 'tentacruel', 'pokedexNo': '073' },
    156: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    157: { 'name': 'goldeen', 'pokedexNo': '118' },
    158: { 'name': 'seaking', 'pokedexNo': '119' },
    159: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    160: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    161: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    162: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    163: { 'name': 'ponyta', 'pokedexNo': '077' },
    164: { 'name': 'rapidash', 'pokedexNo': '078' },
    165: { 'name': 'rattata', 'pokedexNo': '019' },
    166: { 'name': 'raticate', 'pokedexNo': '020' },
    167: { 'name': 'nidorino', 'pokedexNo': '033' },
    168: { 'name': 'nidorina', 'pokedexNo': '030' },
    169: { 'name': 'geodude', 'pokedexNo': '074' },
    170: { 'name': 'porygon', 'pokedexNo': '137' },
    171: { 'name': 'aerodactyl', 'pokedexNo': '142' },
    172: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    173: { 'name': 'magnemite', 'pokedexNo': '081' },
    174: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    175: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    176: { 'name': 'charmander', 'pokedexNo': '004' },
    177: { 'name': 'squirtle', 'pokedexNo': '007' },
    178: { 'name': 'charmeleon', 'pokedexNo': '005' },
    179: { 'name': 'wartortle', 'pokedexNo': '008' },
    180: { 'name': 'charizard', 'pokedexNo': '006' },
    181: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    182: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    183: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    184: { 'name': 'missingno', 'pokedexNo': 'NULL' },
    185: { 'name': 'oddish', 'pokedexNo': '043' },
    186: { 'name': 'gloom', 'pokedexNo': '044' },
    187: { 'name': 'vileplume', 'pokedexNo': '045' },
    188: { 'name': 'bellsprout', 'pokedexNo': '069' },
    189: { 'name': 'weepinbell', 'pokedexNo': '070' },
    190: { 'name': 'victreebel', 'pokedexNo': '071' },
};

export const charMap: Record<number, string> = {
    // Control characters
    0x00: "<NULL>",
    0x49: "<PAGE>",
    0x4A: "<PKMN>", // "<PK><MN>"
    0x4B: "<_CONT>", // implements "<CONT>"
    0x4C: "<SCROLL>",
    0x4E: "<NEXT>",
    0x4F: "<LINE>",
    0x50: "@", // string terminator
    0x51: "<PARA>",
    0x52: "<PLAYER>", // wPlayerName
    0x53: "<RIVAL>", // wRivalName
    0x54: "#", // "POKé"
    0x55: "<CONT>",
    0x56: "<……>", // "……"
    0x57: "<DONE>",
    0x58: "<PROMPT>",
    0x59: "<TARGET>",
    0x5A: "<USER>",
    0x5B: "<PC>", // "PC"
    0x5C: "<TM>", // "TM"
    0x5D: "<TRAINER>", // "TRAINER"
    0x5E: "<ROCKET>", // "ROCKET"
    0x5F: "<DEXEND>",

    // Actual characters
    0x69: "<BOLD_V>",
    0x6A: "<BOLD_S>",
    0x6D: "<COLON>", // colon with tinier dots than ":"
    0x70: "‘", // opening single quote
    0x71: "’", // closing single quote
    0x72: "“", // opening quote
    0x73: "”", // closing quote
    0x74: "·", // middle dot, unused
    0x75: "…", // ellipsis

    0x79: "┌",
    0x7A: "─",
    0x7B: "┐",
    0x7C: "│",
    0x7D: "└",
    0x7E: "┘",
    0x7F: " ",

    // Actual characters (from gfx/font/font.png)
    0x80: "A",
    0x81: "B",
    0x82: "C",
    0x83: "D",
    0x84: "E",
    0x85: "F",
    0x86: "G",
    0x87: "H",
    0x88: "I",
    0x89: "J",
    0x8A: "K",
    0x8B: "L",
    0x8C: "M",
    0x8D: "N",
    0x8E: "O",
    0x8F: "P",
    0x90: "Q",
    0x91: "R",
    0x92: "S",
    0x93: "T",
    0x94: "U",
    0x95: "V",
    0x96: "W",
    0x97: "X",
    0x98: "Y",
    0x99: "Z",

    0x9A: "(",
    0x9B: ")",
    0x9C: ":",
    0x9D: ";",
    0x9E: "[",
    0x9F: "]",

    0xA0: "a",
    0xA1: "b",
    0xA2: "c",
    0xA3: "d",
    0xA4: "e",
    0xA5: "f",
    0xA6: "g",
    0xA7: "h",
    0xA8: "i",
    0xA9: "j",
    0xAA: "k",
    0xAB: "l",
    0xAC: "m",
    0xAD: "n",
    0xAE: "o",
    0xAF: "p",
    0xB0: "q",
    0xB1: "r",
    0xB2: "s",
    0xB3: "t",
    0xB4: "u",
    0xB5: "v",
    0xB6: "w",
    0xB7: "x",
    0xB8: "y",
    0xB9: "z",

    0xBA: "é",
    0xBB: "'d",
    0xBC: "'l",
    0xBD: "'s",
    0xBE: "'t",
    0xBF: "'v",

    0xE0: "'",
    0xE1: "<PK>",
    0xE2: "<MN>",
    0xE3: "-",
    0xE4: "'r",
    0xE5: "'m",
    0xE6: "?",
    0xE7: "!",
    0xE8: ".",

    0xE9: "ァ",
    0xEA: "ゥ",
    0xEB: "ェ",

    0xEC: "▷",
    0xED: "▶",
    0xEE: "▼",
    0xEF: "♂",
    0xF0: "¥",
    0xF1: "×",
    0xF2: "<DOT>", // decimal point; same as "." in English
    0xF3: "/",
    0xF4: ",",
    0xF5: "♀",

    0xF6: "0",
    0xF7: "1",
    0xF8: "2",
    0xF9: "3",
    0xFA: "4",
    0xFB: "5",
    0xFC: "6",
    0xFD: "7",
    0xFE: "8",
    0xFF: "9"

};

